### ISSUE TITLE
401 on first request, all following requests succeed

### ISSUE THREAD

**Issue by hiqmhofmann** [johann-petrak/python-tiny-http-server#6]
With the release of version 0.4 a bug was introduced where the first request would fail with a 401 Unauthorized response even though if one provides the correct basic auth credentials. In all following requests basic auth is then evaluated correctly and the server behaves again as expected. We currently mitigate the issue by using version 0.3 which does not contain this error.

**Comment by johann-petrak** [comment]
Hmmm this was done deliberately in order to force asking for the credentials after a restart: previously, after restarting the server, firefox would send over the "old" basic auth key and access would be possible without authenticating again. 
I guess it is a matter of taste if a server restart SHOULD force re-authentication?

**Comment by johann-petrak** [comment]
There is now a version 0.5 which adds a few new features and also adds option `--no-force-auth` which will avoid forcing the re-authentication after a server re-start. I hope this is useful to you. If there is still a bug or some other problem, feel free to re-open or open a new issue.

**Comment by hiqmhofmann** [comment]
Awesome @johann-petrak , thank you!
